In [1]:
import numpy as np

In [2]:
recipes = np.genfromtxt('recipes.csv', delimiter=',')
print(recipes)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


In [3]:
eggs = recipes [:,2]
print(eggs)

[2. 1. 1. 2.]


In [4]:
eggs == 1

array([False,  True,  True, False])

In [5]:
cupcakes = recipes [0, :]
cookies = recipes [2, :]
print(cupcakes)
print(cookies)

[2.   0.75 2.   1.   0.5 ]
[2.75 1.5  1.   0.   1.  ]


In [6]:
grosery_list = 2*cupcakes + cookies
print(grosery_list)

[6.75 3.   5.   2.   2.  ]


In [7]:
x = np.linspace(0, 10, num=6)
print(x)


[ 0.  2.  4.  6.  8. 10.]
